apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmenter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segmenter
  template:
    metadata:
      labels:
        app: segmenter
    spec:
      containers:
        - name: segmenter
          image: ghcr.io/kloe-b/p2-video-processing-service/p2-segmenter:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              value: AKIASQQQG2XF4V573GL6
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_BUCKET_NAME
              value: flasks3scalable
            - name: REDIS_HOST
              value: "redis-service.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: regcred
            

