apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: video-processing-service
  template:
    metadata:
      labels:
        app: video-processing-service
    spec:
      containers:
        - name: video-processing-service
          image: video-processing-service-image:latest  
          ports:
            - containerPort: 8080  
          env:
            - name: AWS_ACCESS_KEY_ID
              value: AKIASQQQG2XF4V573GL6
            - name: AWS_SECRET_ACCESS_KEY
              value: CdttLTHaOvXicRjrrkBXrqpK2daZNWXeG7fh3uUu
            - name: AWS_BUCKET_NAME
              value: flasks3scalable
            - name: SECRET_KEY
              value: your_secret_key 

