apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-worker
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: thumbnail-worker
  template:
    metadata:
      labels:
        app: thumbnail-worker
    spec:
      containers:
        - name: thumbnail-worker
          image: thumbnail-worker-image:latest  
          ports:
            - containerPort: 8080  
          env:
            - name: THUMBNAIL_DIR
              value: thumbnails
            - name: SECRET_KEY
              value: your_secret_key 