name: Build and Push Backend Converter Docker Image
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build 
        uses: docker/build-push-action@v5
        with:
          context: ./docker/converter
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.BASE_IMG_NAME }}/converter_worker:latest

  
      - name: Publish the images
        run: docker push ghcr.io/${{ env.BASE_IMG_NAME }}/converter_worker:${{ steps.vars.outputs.sha_short }}
             docker push ghcr.io/${{ env.BASE_IMG_NAME }}/converter_worker:latest